version: "3.8"
services:
  workspace:
    image: rootproject/root:latest
    user: root
    init: true
    volumes:
      - ..:/workspace:cached
    # This just tells Compose to start ollama first
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
